version: '3.8'

networks:
  traefik:
    external: true
  frontzap-internal:
    driver: bridge

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: frontzap-postgres
    restart: unless-stopped
    networks:
      - frontzap-internal
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-frontzap}
      POSTGRES_USER: ${POSTGRES_USER:-frontzap}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-frontzap} -d ${POSTGRES_DB:-frontzap}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: frontzap-redis
    restart: unless-stopped
    networks:
      - frontzap-internal
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "auth", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontzap Application
  frontzap:
    image: frontzap:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontzap-app
    restart: unless-stopped
    networks:
      - traefik
      - frontzap-internal
    environment:
      # Database
      DATABASE_URL: postgresql://${POSTGRES_USER:-frontzap}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-frontzap}
      
      # Supabase
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      
      # Stripe
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      
      # N8N
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      N8N_API_KEY: ${N8N_API_KEY}
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      # App
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: https://${DOMAIN}
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      
      # HTTP Router
      - "traefik.http.routers.frontzap.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontzap.entrypoints=websecure"
      - "traefik.http.routers.frontzap.tls=true"
      - "traefik.http.routers.frontzap.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontzap.loadbalancer.server.port=3000"
      
      # Security Headers
      - "traefik.http.routers.frontzap.middlewares=frontzap-headers"
      - "traefik.http.middlewares.frontzap-headers.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE,PATCH"
      - "traefik.http.middlewares.frontzap-headers.headers.accesscontrolalloworiginlist=https://${DOMAIN}"
      - "traefik.http.middlewares.frontzap-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.frontzap-headers.headers.addvaryheader=true"
      - "traefik.http.middlewares.frontzap-headers.headers.referrerpolicy=same-origin"
      - "traefik.http.middlewares.frontzap-headers.headers.framedeny=true"
      - "traefik.http.middlewares.frontzap-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.frontzap-headers.headers.browserxssfilter=true"

  # N8N Automation Platform
  n8n:
    image: n8nio/n8n:latest
    container_name: frontzap-n8n
    restart: unless-stopped
    networks:
      - traefik
      - frontzap-internal
    environment:
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: ${N8N_USER:-admin}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_PASSWORD}
      N8N_HOST: n8n.${DOMAIN}
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://n8n.${DOMAIN}
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_METRICS: true
      N8N_LOG_LEVEL: info
    volumes:
      - n8n_data:/home/node/.n8n
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  n8n_data:
    driver: local
